// Plugins are declared here and resolved by settings.gradle.
plugins {
    id 'com.android.application' version '8.13.0' apply false
    id 'com.google.gms.google-services' version '4.4.4' apply false
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

